name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.base_ref }} == "1-21" ]; then
            echo "Merge requests to/from 1-21 branch are disallowed."
            exit 1
          fi
          if [ ${{ github.head_ref }} == "1-21" ]; then
            echo "Merge requests to/from 1-21 branch are disallowed"
            exit 1
          fi
